services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talleres-app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    restart: always
    mem_limit: 512M

  db:
    image: mariadb:11.4.2
    container_name: talleres-db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: yourpassword
      MARIADB_DATABASE: talleres
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    mem_limit: 256M

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: talleres-phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
    mem_limit: 128M

volumes:
  db_data:


networks:
  default:
    name: "talleres-network"
