FROM composer:2.7.7 AS composer-deps

COPY composer.json composer.lock /temp/prod/

WORKDIR /temp/prod

RUN composer install --no-interaction --prefer-dist --no-dev --no-scripts --no-progress
RUN composer dump-autoload --optimize

FROM oven/bun:1-alpine AS bun-base

FROM bun-base AS node-deps

COPY package.json bun.lockb /temp/dev/

WORKDIR /temp/dev

RUN bun install --frozen-lockfile

COPY package.json bun.lockb /temp/prod/

WORKDIR /temp/prod

RUN bun install --frozen-lockfile --production

FROM bun-base AS bun-build

WORKDIR /app

COPY --from=node-deps /temp/dev/node_modules node_modules
COPY . .

RUN bun run build

FROM php:8.0-apache

WORKDIR /var/www/html

# Deps
COPY --from=composer-deps /temp/prod/vendor vendor
COPY --from=node-deps /temp/prod/node_modules node_modules

COPY --from=bun-build /app/package.json .

# Code
COPY --from=bun-build /app/public public
COPY --from=bun-build /app/src src

# PHP Modules
RUN docker-php-ext-install mysqli
RUN a2enmod rewrite

# Apache conf
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Envs
ARG MYSQLHOST
ARG MYSQLUSER
ARG MYSQLPASSWORD
ARG MYSQLDATABASE
ARG MYSQLPORT

ARG PANEL_ADMIN_PASSWORD

ENV LOADENV=OK DB_HOST=${MYSQLHOST} DB_USER=${MYSQLUSER} DB_PASSWORD=${MYSQLPASSWORD} DB_DATABASE=${MYSQLDATABASE} DB_PORT=${MYSQLPORT} PANEL_ADMIN_PASSWORD=${PANEL_ADMIN_PASSWORD}

EXPOSE 80

CMD [ "apache2-foreground" ]